# Generated by Django 5.2.7 on 2025-12-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sukubunData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField()),
            ],
        ),
    ]
