# Generated by Django 5.2.7 on 2025-12-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sukubundata',
            name='note',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
