# Generated by Django 5.2.7 on 2025-12-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0002_sukubundata_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sukubundata',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]
