# Generated by Django 5.2.7 on 2025-12-26 10:07

import demos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0003_alter_sukubundata_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sukubundata',
            name='create_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sukubundata',
            name='file',
            field=models.FileField(storage=demos.models.OverwriteStorage(), upload_to=demos.models.sukubun_path),
        ),
    ]
