# Generated by Django 5.2.7 on 2026-01-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0004_alter_sukubundata_create_at_alter_sukubundata_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sukubundata',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
