"""
Django settings for inviasvivo project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
# Google storage
from google.oauth2 import service_account
from google.cloud import storage



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-29xc2o74hq4w%@f1!o4&)^n&+k%h@c1xwg^3t0k!65um&bkzo2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CORS_ALLOW_ALL_ORIGINS = True

# CORS

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:9000",
]

# CORS ALLOW

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'authorization',
    'content-type',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'storages',
    'frontend',
    'backend',
    'demos',
    'clase',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'inviasvivo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inviasvivo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Development line
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Production line
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Url del lenguaje R
# RSCRIPT_PATH = r""

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField' # Permiso para almacenamiento de datos de gran carga
GS_CREDENTIALS = os.environ.get('GOOGLE_APPLICATION_CREDENTIALS') # Accesos a la llave privada

DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage' # Acceso al Google Cloud
GS_BUCKET_NAME = 'invias' # Nombre del bucket objetivo
GS_PROJECT_ID = 'complete-energy-448804-i2' # Identificador del bucket objetivo




# GS_BUCKET_NAME = 'invias_mapa_vulnerabilidad_faunistica' # Nombre del bucket objetivo
# GS_PROJECT_ID = 'geoinformatica-442522' # Identificador del bucket objetivo
# Credentials
# Enlace de archivos
# MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/'


######################################################################
######################################################################

# # Ruta al archivo JSON
# ruta_credenciales = "C:\Program Files\Ampps\www\inviasvivo\inviasvivo\credentials\credentials.json"

# print(ruta_credenciales)

# Crear credenciales
# credentials = service_account.Credentials.from_service_account_file(ruta_credenciales)


# credentials = service_account.Credentials.from_service_account_file(
#     "credentials/credentials.json"
# )

# client = storage.Client(credentials=credentials)
# bucket = client.bucket("invias")

# print('directorio'+os.getcwd()+'\credentials')
# print(os.path.exists(os.getcwd()+'/credentials/credentials.json'))

# from google.cloud import storage

# def read_gcs_file_line_by_line(bucket_name, file_name):
#     client = storage.Client()

#     bucket = client.bucket(bucket_name)
#     blob = bucket.blob(file_name)
#     content = blob.download_as_text()

#     for line in content.splitlines():
#         print(line)

# read_gcs_file_line_by_line("invias", "maps_invias/mapa.geojson")



#####################################################################
#####################################################################
#===================================================================# 
# def read_all_files_in_directory(bucket_name, prefix):
#     client = storage.Client()
#     bucket = client.bucket(bucket_name)

#     blobs = bucket.list_blobs(prefix=prefix)

#     for blob in blobs:
#         print(f"\n=== Leyendo archivo: {blob.name} ===")

#         content = blob.download_as_text()
#         for line in content.splitlines():
#             print(line)

# read_all_files_in_directory("invias", "maps_invias/geojson/")


##########################################################################
#========================================================================#
# def list_blobs(bucket_name):
#     """Lists all the blobs in the bucket."""
#     # bucket_name = "your-bucket-name"
#     storage_client = storage.Client()
#     blobs = storage_client.list_blobs(bucket_name)

    
#     for blob in blobs:
#         print(blob.name)


# list_blobs('invias')