"""
Django settings for inviasvivo project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
# Google storage
from google.oauth2 import service_account
from google.cloud import storage

from celery.schedules import crontab





# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-29xc2o74hq4w%@f1!o4&)^n&+k%h@c1xwg^3t0k!65um&bkzo2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CORS_ALLOW_ALL_ORIGINS = True

# CORS

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:9000",
]

# CORS ALLOW

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'authorization',
    'content-type',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework',
    # 'django_crontab',
    'django_celery_beat',
    'corsheaders',
    'storages',
    'frontend',
    'backend',
    'demos',
    'clase',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'inviasvivo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inviasvivo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Development line
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_ROOT = BASE_DIR / "media"

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Production line
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Url del lenguaje R
# RSCRIPT_PATH = r""

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField' # Permiso para almacenamiento de datos de gran carga
GS_CREDENTIALS = os.environ.get('GOOGLE_APPLICATION_CREDENTIALS') # Accesos a la llave privada

# DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage' # Acceso al Google Cloud
# GS_BUCKET_NAME = 'invias' # Nombre del bucket objetivo
# GS_PROJECT_ID = 'complete-energy-448804-i2' # Identificador del bucket objetivo

GS_CREDENTIALS_FILE = "C:\Program Files\Ampps\www\inviasvivo\inviasvivo\credentials\credentials.json"

# GCS_CREDENTIALS_FILE = BASE_DIR / ruta_credenciales

print('credeciales aca')
print(GS_CREDENTIALS_FILE)

GS_BUCKET_NAME = 'invias_mapa_vulnerabilidad_faunistica' # Nombre del bucket objetivo
GS_PROJECT_ID = 'geoinformatica-442522' # Identificador del bucket objetivo

EXPORTS_DIR = MEDIA_ROOT / "exportsGCS"

# Credentials
# Enlace de archivos
# MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/'

# CRONJOBS = []
#     ('*/5 * * * *', 'demos.cron.my_scheduled_job'),  # cada 5 minutos
# ]



###############################################################################
# =====================
# GEE / EXPORT SETTINGS
# =====================

GEE_MASK_SHP = BASE_DIR / "data/mask200_Dissolve.shp"
GEE_OUTPUT_DIR = BASE_DIR / "data/ARQ_TESELAS"

GEE_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

PREFERRED_SPLIT_FIELDS = [
    "DPTO", "DEPARTAMEN", "NOMBRE_DPT", "NOM_DEPTO", "DEPARTAMENTO"
]

REGION_SIZE_KM = 300
TILE_SIZE_KM = 50
OVERLAP_KM = 0

MAX_CONCURRENT = 3
PAUSE_BETWEEN = 0.2

MAX_SPLIT_DEPTH = 3
MIN_TILE_KM = 3

WRITE_TILES_SHP_PER_ZONE = True
WRITE_TILES_SHP_GLOBAL = True

# =====================
# GEE AUTH
# =====================

GEE_SA_EMAIL = "geoinformatica-442522@geoinformatica-442522.iam.gserviceaccount.com"
GEE_SA_KEY = BASE_DIR / "credentials/geoinformatica.json"
GEE_PROJECT_ID = "geoinformatica-442522"

GCS_BUCKET = "invias_mapa_vulnerabilidad_faunistica"
GCS_PREFIX = "s2/2025Q4"

CRS_EXPORT = "EPSG:4326"
SCALE_EXPORT_M = 100
EXPORT_COG = True

